/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Tab,
} from './tabs';

export namespace Components {
  interface AboutTab {}
  interface AppRoot {}
  interface FlipCard {
    'height': number;
    'rotateDegrees': number;
    'width': number;
  }
  interface HomeTab {}
  interface ProjectsTab {}
  interface TabBar {
    'activeTab': Tab;
    'tabs': Tab[];
    'width': number;
  }
}

declare global {


  interface HTMLAboutTabElement extends Components.AboutTab, HTMLStencilElement {}
  var HTMLAboutTabElement: {
    prototype: HTMLAboutTabElement;
    new (): HTMLAboutTabElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFlipCardElement extends Components.FlipCard, HTMLStencilElement {}
  var HTMLFlipCardElement: {
    prototype: HTMLFlipCardElement;
    new (): HTMLFlipCardElement;
  };

  interface HTMLHomeTabElement extends Components.HomeTab, HTMLStencilElement {}
  var HTMLHomeTabElement: {
    prototype: HTMLHomeTabElement;
    new (): HTMLHomeTabElement;
  };

  interface HTMLProjectsTabElement extends Components.ProjectsTab, HTMLStencilElement {}
  var HTMLProjectsTabElement: {
    prototype: HTMLProjectsTabElement;
    new (): HTMLProjectsTabElement;
  };

  interface HTMLTabBarElement extends Components.TabBar, HTMLStencilElement {}
  var HTMLTabBarElement: {
    prototype: HTMLTabBarElement;
    new (): HTMLTabBarElement;
  };
  interface HTMLElementTagNameMap {
    'about-tab': HTMLAboutTabElement;
    'app-root': HTMLAppRootElement;
    'flip-card': HTMLFlipCardElement;
    'home-tab': HTMLHomeTabElement;
    'projects-tab': HTMLProjectsTabElement;
    'tab-bar': HTMLTabBarElement;
  }
}

declare namespace LocalJSX {
  interface AboutTab extends JSXBase.HTMLAttributes<HTMLAboutTabElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface FlipCard extends JSXBase.HTMLAttributes<HTMLFlipCardElement> {
    'height'?: number;
    'rotateDegrees'?: number;
    'width'?: number;
  }
  interface HomeTab extends JSXBase.HTMLAttributes<HTMLHomeTabElement> {}
  interface ProjectsTab extends JSXBase.HTMLAttributes<HTMLProjectsTabElement> {}
  interface TabBar extends JSXBase.HTMLAttributes<HTMLTabBarElement> {
    'activeTab': Tab;
    'onTabChange'?: (event: CustomEvent<any>) => void;
    'tabs': Tab[];
    'width': number;
  }

  interface IntrinsicElements {
    'about-tab': AboutTab;
    'app-root': AppRoot;
    'flip-card': FlipCard;
    'home-tab': HomeTab;
    'projects-tab': ProjectsTab;
    'tab-bar': TabBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


